/**:
  ros__parameters:
    verbose: false

    planning_hz: 10.0
    backward_path_length: 0.0    # 元々5.0 経路生成の際にどれくらい先までの経路を生成するかを変えることができ
    forward_path_length: 20.0    # 元々300.0
    backward_length_buffer_for_end_of_pull_over: 5.0
    backward_length_buffer_for_end_of_pull_out: 5.0
    minimum_pull_over_length: 16.0

    refine_goal_search_radius_range: 7.5

    # parameters for turn signal decider
    turn_signal_intersection_search_distance: 30.0
    turn_signal_intersection_angle_threshold_deg: 15.0 
    turn_signal_minimum_search_distance: 1.0 # 元々10.0
    turn_signal_search_time: 1.0 # 元々3.0
    turn_signal_shift_length_threshold: 0.1 # 元々0.3
    turn_signal_on_swerving: true

    # 経路を生成する時の解像度に関するパラメータ
    # 大きいと荒すぎる経路が生成されるが、小さすぎると計算コストが高くなってしまう。
    path_interval: 0.1   #元々2.0

    visualize_maximum_drivable_area: true

    lateral_distance_max_threshold: 1.5 # 元々2.0
    longitudinal_distance_min_threshold: 1.0 # 元々3.0

    expected_front_deceleration: -1.0
    expected_rear_deceleration: -1.0

    expected_front_deceleration_for_abort: -1.0
    expected_rear_deceleration_for_abort: -2.0

    rear_vehicle_reaction_time: 2.0
    rear_vehicle_safety_time_margin: 1.0

    # USE ONLY WHEN THE OPTION COMPILE_WITH_OLD_ARCHITECTURE IS SET TO FALSE.
    # https://github.com/autowarefoundation/autoware.universe/blob/main/planning/behavior_path_planner/CMakeLists.txt
    # NOTE: The smaller the priority number is, the higher the module priority is.

    # Change the 'enable_module' flag for the following modules to 'false' to try Autoware-Mini

    lane_change:
      enable_module: true
      # enable_module: false
      enable_simultaneous_execution: false
      priority: 4
      max_module_size: 1

    pull_out:
      enable_module: true
      # enable_module: false
      enable_simultaneous_execution: false
      priority: 1 # 元々0
      max_module_size: 1

    side_shift:
      enable_module: true
      # enable_module: false
      enable_simultaneous_execution: false
      priority: 3 # 元々2
      max_module_size: 1

    pull_over:
      enable_module: true
      # enable_module: false
      enable_simultaneous_execution: false
      priority: 2  # 元々1
      max_module_size: 1

    avoidance:
      enable_module: true
      # enable_module: false
      enable_simultaneous_execution: false
      priority: 0 #　元々3
      max_module_size: 1
